### ISSUE TITLE
Click and Move can not work well

### ISSUE THREAD

**Issue by s949492225** [skhugh/Android-Simple-PullToRefresh#1]
in listView,the click event will also be executed when pull down;
in recycleView, if you set item's view onClickListener,you will can not pull down ,it can not work;
The two error is very serious，Maybe you should make it be perfect.
thanks !

**Comment by skhugh** [comment]
@s949492225 Thanks for the heads up.
I have fixed both problems on the new commit.
I have also added onItemClickListener to ListView sample and onClickListener to RecyclerView sample so you can check them out.
Use 'com.skhugh.simplepulltorefresh:simplepulltorefresh:1.0.2' if you are using gradle.

If the problem exists or any other bug pops up please let me know. Thanks.
